### ISSUE TITLE
Project approval

### ISSUE THREAD

**Issue by xiaoa0** [xiaoa0/abacus#10]
### Concept
Online abacus multiplayer game where players can join public or private games
Select number of digits and operations for problems before starting
Solo mode with self-inputted or generated problems
Will use arrays to track keyboard input to abacus class

### [Wireframes](https://docs.google.com/presentation/d/1b3WYjMRqn8y0K4cHxF-50bNecGHf38iZxflXX4Em-Qk/edit?usp=sharing)
[Examples](https://docs.google.com/presentation/d/1Oy3eYeCfdiqzdH_BoKOGf6ozwopNN2m37iuvRdqOFmw/edit?usp=sharing)

### Work plan

Start by building abacus display and operations with keyboard controls
Focus on optimizing response time, possibly with Javascript
Random problem generator that takes number of digits as parameter
Multiplayer games come after basics

-----
### Individual work
[Allie](https://github.com/xiaoa0/fastpages_test/issues/11)
[Avinh](https://slimeyturtles.github.io/VSCODE/week6/0)
[Soren](https://github.com/wangzi190/apcsa-tri1/issues/10)

**Comment by jm1021** [comment]
Project wireframe.  A lot of static information.  Digital Ab.  Account system.  Save user progress and strength.  

Avinh..  Problem with using Notebooks.  ASCII derivative is interesting.  2.7
Allie..  Poky and all standard work and effort 2.7
Soren ..   Shared some standard information.  Random joke API 2.6.

**Comment by 7unlim** [comment]
- Project wireframe 
- Discussed account system: saving user progress
- Good RapidAPI work for all members

2.7/3
