### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by xiaoa0** [xiaoa0/abacus#12]
### [Video](https://drive.google.com/file/d/1FtoEiG4K2izp3-ZuSDu2vsq68L3P9xzS/view?usp=sharing)

Scrum (Allie): https://drive.google.com/file/d/1OOWtgk51IlY6Q1D4wibnzGzm3Jf67CuE/view?usp=sharing

Frontend (Soren): https://www.loom.com/share/db4f144872c14cfbbe16535aacb01277

Backend (Avinh): https://drive.google.com/file/d/1--vFocn3alT92zZEsQiMKwLr7pGcYP5P/view?usp=sharing

Deployment (Michael):

**Comment by SlimeyTurtles** [comment]
https://drive.google.com/file/d/1zOWtHiScHSek1PWG8yS6ipkNZSKYNZSg/view?usp=sharing

**Comment by jm1021** [comment]
Good concepts planning, FE, and object in BE.  I do see you working and seems like there is some excitement in task.  I kind of get it, but if it wasn't for watching and quick demos I might be more lost.   My hope is Allie has some coding job as well as Scrum Master.   4.4/5
