### ISSUE TITLE
Project brainstorming

### ISSUE THREAD

**Issue by xiaoa0** [xiaoa0/abacus#2]
### Abacus game

- Website to teach the basics of using an abacus
- Informational page as well as competitive practice/game mode
- Practice page where user is given calculations to do (can select difficulty)
- Competition mode where user can play against another user or a bot, each win/loss leads to change in digits of calculations (5-20)

### Work delegation

- Soren: teach/refer to resources for how an abacus works (probably cover info page?), code other miscellaneous features
- Avinh and Allie: integrate main features along with Soren, work on CSS styling
- Michael: deployment/other assignments

> abacus battle royal:
> 
>     * like tetris 99 for abacus

**Comment by SlimeyTurtles** [comment]
self driving rc cars. We teach them with neural networks and cameras and they race

**Comment by SlimeyTurtles** [comment]
traffic visualizer:
- we set up cameras to record license plates on streets
- we put the licenseplates/locations/time in a db
- difference in time/space per license plate can help us visualize speed
- we colorize a map like google maps to see the flow of traffic around us in dnhs

**Comment by SlimeyTurtles** [comment]
trash robots:
- like little walles that pick up trash
- they can dap eachother up
- the principal is happy with us
- like roomablas

**Comment by SlimeyTurtles** [comment]
note takers:
- a neural network that i feel my notes and where i got the notes from so it learns how to take more notes

**Comment by SlimeyTurtles** [comment]
whiteboard calculator:
- a calculator that can be visualized on a white board
- say "do 2+2" and it will display "2 + 2 = 4" on a JFrame whiteboard
- say "Grab the gravitation equation" and the gravitation equation appears, then say "plug in 26 kg for M1, 12 kg for M2, and 26 meters for R" and it replaces the variable or declares the variables somewhere and solves as if you were to do it on a white board
- add features for derivatives/integrals and gradually over time we can add patches for higher levels of math

**Comment by SlimeyTurtles** [comment]
abacus battle royal:
- like tetris 99 for abacus
