### ISSUE TITLE
Team lesson

### ISSUE THREAD

**Issue by xiaoa0** [xiaoa0/abacus#3]
# Methods
- [AP FRQ](https://xiaoa0.github.io/fastpages_test/collegeboard/2022/09/16/frq1.html)
- Essentially a function in Java that can be called after being defined in a class
- Use methodName(); syntax to call
```
public static int numberOfLeapYears(int year1, int year2) {
   int counter = int year1;
   for (int a = year1; a <= year2; a++) { // taking a as a parameter, setting boundaries as between year1 and year2
      if (isLeapYear(a)) { // checking if year value is leapyear
         counter++; // adding 1 to counter if true
         }
      }
   return counter; // returning final count after 
   }
```

# Control Structures
- [Case handling with scanner input](https://xiaoa0.github.io/fastpages_test/jupyter/2022/09/02/javaterminal.html)
- Used to handle exceptions and selection
- Main ones are if/else (with or without case handling) and for/while loops
```
if(condition 1) {
    // code for if condition is true
} else if (condition 2) {
    // code for if condition 2is true
} else if (condition 3) {
    // code for if condition 3 is true
} else {
    // code for if all other conditions are false
}
```
- [For loop](https://xiaoa0.github.io/fastpages_test/jupyter/2022/09/13/monkeys.html)
```for (int col = 0; col < monkeys[rowCount].length; col++) {

                for (int row = 0; row < monkeyCount; row++) {  //cycles through "cells" of 2d array

                    // prints specific part of the monkey from the column
                    System.out.print(monkeys[row][col] + " ");

                }

                //this new line gives separation between stanza of poem
                System.out.println();
            }
```

### Other references
W3SCHOOLS
- [Methods](https://www.w3schools.com/java/java_methods.asp)
- [For loop](https://www.w3schools.com/java/java_for_loop.asp)
- [While loop](https://www.w3schools.com/java/java_while_loop.asp)
- [If/else](https://www.w3schools.com/java/java_conditions.asp)

**Comment by jm1021** [comment]
No evidence of team planning.  
Allie - 2017 leap year and day of the week describe.   Discussed algorithms and had a nicely commented Jupyter notebook.  Easy to follow, not anything extra.
Soren - 2018 frog simulation.  Jupyter notebook has solution but not much documentation.  Scattered in presentation.  More animated, but a little harder to follow.
Allie again - described former work.  Horizontal shown.

2.6 as not enough on Mondays

2.4 for Avinh and Michael

**Comment by xiaoa0** [comment]
### Self-grading comments

Allie: 2.6/3. Finished all work and presented FRQ + other concepts, but was unprepared.
Soren: 2.7. Did all work and presented FRQ + key lesson concepts.
Avinh: 2.25/3. Did some of the monkey code, but didn't finish and didn't do part of the presentation.
