### ISSUE TITLE
Week 5

### ISSUE THREAD

**Issue by xiaoa0** [xiaoa0/abacus#8]
### [Wireframes](https://docs.google.com/presentation/d/1Oy3eYeCfdiqzdH_BoKOGf6ozwopNN2m37iuvRdqOFmw/edit?usp=sharing)
[Scrum board](https://github.com/users/xiaoa0/projects/1)
[Brainstorming](https://github.com/xiaoa0/springportfolio/issues/2)

-----
- [Allie](https://github.com/xiaoa0/fastpages_test/issues/9)
- Soren
- [Avinh](https://slimeyturtles.github.io/VSCODE/week5/0)

**Comment by NathanManangan** [comment]
# Score 2.7/3
- [x] Google Slides
- [x] games on front page
- [x] front end, rando, buttons, etc
- [x] Didnt use extends
- [x] Fibo, JS not quite done

**Comment by samayasankuratri** [comment]
2.7/3
### PBL
Showed Wireframes with key features they want to implement
Private games 
Explained how they plan on coding Abacus
Explained how they will be able to translate their idea with backend

### Hacks
Fibonacci - Showed algorithm understanding but should show extends - as extra added timer
Did not finish JavaScript UI

**Comment by jm1021** [comment]
Abacus teaching sites.   Solo mode, Team mode (competition real time). 

FE. Google slides yuk!  Has menu's settings and visuals.  Blogging would have allowed Soren to write some of her comments.  

BE. Discussed Game Obj and User Obj.  Shared 2D array and discussed more on data management.   Once again, details could have been better .

Allie discussed Fib, but wrote main algorithm.   
Avinh main loops, but added timing.
Soren no labs.

2.4 for Avinh, Allie
2.1 Soren

**Comment by tangalice** [comment]
2.7/3

slideshow with PBL plans (gaming website)
- private and public games
- among us game screenshots as wireframes
- explained code plan for abacus game
- 2D array explanation for abacus

no extends on fibonacci hacks
Avinh added a timer to fibonacci calculator but also did not extend fibo

did not finish javascript UI feature

**Comment by NicholasRamos5** [comment]
Overall given score: 2.7/3
-  Elaborated on their brainstorming
- Talked about front end and design processes 
- Touched on how the game/website physically works
- Backend: objects interacting with each other
- 2d array displays abacus values explanation
- Explained how an abacus normally works, and went through how that impacted their code
-  Explained how to increase speed for Abacus

- Used and went over loops (while, for, recursion) 
- Talked about speed of each, which one is more efficient

- Should work on utilizing extends (code.org learnings)

**Comment by iriisyang** [comment]
2.7/3
- interactive game based website for abacus
- explain how to increase speed for abacus
- no extension for fibonacci
- added timer for different methods

**Comment by icyGS** [comment]
2.7/3
- Abacus game
- Explained how to use the game page well
- Win or loss screen
- Objects interacting with each other in a 2D array
- Multiple features

**Comment by sarayu-pr11** [comment]
2.7/3
- game website to teach people abacus
- real time gaming
- maybe if you used canva or figma instead of google slides?
- the calculator is meant for speed and efficency
- detailed controls
- maybe if technicals were included for the object description for better understandment?
- team seemed cohesive about the pbl idea
- did the fib hacks but next time maybe you should use extends in the code
- included a timer
-

**Comment by dontran15** [comment]
### 2.7+/3.0
- Idea is very fun
- Singleplayer 
- Multiplayer in real-time 
- Abacus game w/ states being updated constantly
- Has required Fibonacci hack but doesn't extend
- Missing JS
